# Generated by Django 4.0.3 on 2022-11-04 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessTokens',
            fields=[
                ('token', models.TextField(primary_key=True, serialize=False)),
                ('valid_to', models.DateTimeField(default=None)),
            ],
            options={
                'db_table': 'pr_access_tokens',
            },
        ),
        migrations.CreateModel(
            name='RefreshTokens',
            fields=[
                ('token', models.TextField(primary_key=True, serialize=False)),
                ('valid_to', models.DateTimeField(default=None)),
                ('access', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='identification.accesstokens')),
            ],
            options={
                'db_table': 'pr_refresh_tokens',
            },
        ),
    ]
