# Generated by Django 4.0.2 on 2022-11-13 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identification', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtokens',
            name='access',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='identification.accesstokens'),
        ),
    ]
