# Generated by Django 4.0.3 on 2022-11-04 15:03

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Тайтл')),
                ('description', models.TextField(verbose_name='Описание')),
                ('text', tinymce.models.HTMLField(verbose_name='Текст')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Создано')),
                ('views', models.IntegerField(blank=True, default=0, verbose_name='Просмотров')),
                ('image', models.ImageField(default='no_photo.png', upload_to='news')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'db_table': 'fc_news',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NewsCommentary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('parent_id', models.IntegerField(blank=True, null=True, verbose_name='Комментарий-родитель')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'db_table': 'fc_news_comments',
                'ordering': ['id'],
            },
        ),
    ]
