# Generated by Django 4.0.3 on 2022-11-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac_news', '0003_alter_news_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='not-found.png', upload_to='news'),
        ),
    ]
