version: '3.8'

services:

  # БД
  db:
    image: postgres:14-alpine
    volumes:
      - db-vol:/var/lib/postgresql/data
    container_name: database
    user: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Сервер
  server:
    depends_on:
      - db
    build: ./server
    container_name: server
    command: bash -c "python manage.py collectstatic && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - django-media:/usr/portal/server/media
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
    env_file:
      - .env
    restart: on-failure

  # Клиент
  client:
    build: ./client
    container_name: client
    command: npm run start
    env_file:
      - .env
    ports:
      - "443:3000"
      - "80:3000"
      - "3000:3000"
    restart: on-failure

volumes:
  db-vol:
  django-media: