# Generated by Django 4.0.3 on 2022-11-04 15:03

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='Название области')),
            ],
            options={
                'verbose_name': 'Область технологий',
                'verbose_name_plural': 'Области технологий',
                'db_table': 'fc_area_tech',
            },
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('description', models.CharField(default='Нет описания', max_length=1024, verbose_name='Описание')),
                ('image', models.ImageField(default='no_photo.png', upload_to='laboratories')),
                ('text', models.TextField(default='', verbose_name='Информация')),
            ],
            options={
                'verbose_name': 'Лаборатория',
                'verbose_name_plural': 'Лаборатории',
                'db_table': 'fc_laboratories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('information', tinymce.models.HTMLField(verbose_name='Текст')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален?')),
                ('is_moderated', models.BooleanField(default=False, verbose_name='Промодерирован?')),
                ('source', models.TextField(blank=True, default=None, null=True, verbose_name='Ссылка на источник')),
                ('image', models.ImageField(default='no_photo.png', upload_to='projects')),
                ('areas', models.ManyToManyField(blank=True, to='laboratories.area', verbose_name='Области технологий')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'db_table': 'fc_projects',
                'ordering': ['id'],
            },
        ),
    ]
