# Generated by Django 4.0.3 on 2022-11-04 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0001_initial'),
        ('structure', '0001_initial'),
        ('laboratories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Контрибьюторы'),
        ),
        migrations.AddField(
            model_name='project',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='project_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='lab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratories.laboratory', verbose_name='Лаборатория'),
        ),
        migrations.AddField(
            model_name='project',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='project_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.specialty', verbose_name='Направление'),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.tags', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='project',
            name='teamlead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teamlead', to=settings.AUTH_USER_MODEL, verbose_name='Главный разработчик'),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='areas',
            field=models.ManyToManyField(blank=True, to='laboratories.area', verbose_name='Области технологий'),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.tags', verbose_name='Теги'),
        ),
    ]
