# Generated by Django 4.0.2 on 2022-11-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('laboratories', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='areas',
            field=models.ManyToManyField(blank=True, to='laboratories.Area', verbose_name='Области технологий'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.Tags', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='project',
            name='areas',
            field=models.ManyToManyField(blank=True, to='laboratories.Area', verbose_name='Области технологий'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.Tags', verbose_name='Теги'),
        ),
    ]
