# Generated by Django 4.0.3 on 2022-11-27 08:55

from django.db import migrations, models
import src.modules.user.user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_person_groups_alter_person_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='avatar',
            field=models.ImageField(blank=True, default='not-found.png', null=True, upload_to=src.modules.user.user.models.upload_to, verbose_name='Аватар'),
        ),
    ]
