# Generated by Django 4.0.3 on 2022-11-04 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FistLessoner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('patronymic', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.department')),
            ],
            options={
                'verbose_name': 'Преподаватель (КШ)',
                'verbose_name_plural': 'Преподаватели (КШ)',
                'db_table': 'pr_school_teacher',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название направления')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date_start', models.DateField(verbose_name='Дата начала')),
                ('date_end', models.DateField(verbose_name='Дата окончания')),
                ('is_deleted', models.BooleanField(default=False)),
                ('lessoners', models.ManyToManyField(to='fist_school.fistlessoner')),
                ('tags', models.ManyToManyField(to='tags.tags')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
                'db_table': 'co_direction',
                'ordering': ['id'],
            },
        ),
    ]
