# Generated by Django 4.0.2 on 2022-11-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('fist_school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='lessoners',
            field=models.ManyToManyField(to='fist_school.FistLessoner'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='tags',
            field=models.ManyToManyField(to='tags.Tags'),
        ),
    ]
