# Generated by Django 4.0.3 on 2022-11-04 15:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Комментарий')),
                ('parent_id', models.IntegerField(blank=True, default=None, null=True, verbose_name='Ответ на комментарий №')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'db_table': 'fc_idea_comments',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название идеи')),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('information', tinymce.models.HTMLField(verbose_name='Описание задумки')),
                ('is_moderated', models.BooleanField(default=False, verbose_name='Промодерировано?')),
                ('image', models.ImageField(default='no_photo.png', upload_to='ideas/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Идея',
                'verbose_name_plural': 'Идеи',
                'db_table': 'fc_ideas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(verbose_name='Ссылка')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas.idea')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
                'db_table': 'fc_idea_links',
                'ordering': ['id'],
            },
        ),
    ]
