# Generated by Django 4.0.3 on 2022-11-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratories', '0001_initial'),
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='area_tech',
            field=models.ManyToManyField(to='laboratories.area'),
        ),
    ]
