# Generated by Django 4.0.2 on 2022-11-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratories', '0002_initial'),
        ('tags', '0001_initial'),
        ('ideas', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='area_tech',
            field=models.ManyToManyField(to='laboratories.Area'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='tags',
            field=models.ManyToManyField(to='tags.Tags', verbose_name='Теги'),
        ),
    ]
