# Generated by Django 4.0.3 on 2022-11-27 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0004_alter_idea_area_tech_alter_idea_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='idea',
            field=models.ForeignKey(default='not-found.png', on_delete=django.db.models.deletion.CASCADE, to='ideas.idea', verbose_name='Идея'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='image',
            field=models.ImageField(default='not-found.png', upload_to='ideas/', verbose_name='Изображение'),
        ),
    ]
