# Generated by Django 4.0.3 on 2022-11-04 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import src.modules.work.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('tags', '0001_initial'),
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('information', models.TextField(verbose_name='Информация')),
                ('address', models.CharField(max_length=256, verbose_name='Адрес')),
                ('avatar', models.ImageField(default='no_photo.png', upload_to=src.modules.work.models.upload_image_to, verbose_name='Аватар')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'db_table': 'wrk_companies',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Название навыка')),
            ],
            options={
                'verbose_name': 'Скил',
                'verbose_name_plural': 'Скилы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Тайтл')),
                ('description', models.CharField(default='', max_length=1024, verbose_name='Описание')),
                ('salary_min', models.IntegerField(blank=True, null=True, verbose_name='Минимальная зп')),
                ('salary_max', models.IntegerField(blank=True, null=True, verbose_name='Максимальная зп')),
                ('currency_type', models.CharField(blank=True, max_length=5, null=True, verbose_name='Тип валюты')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('email', models.CharField(max_length=32, verbose_name='Почта')),
                ('trash', models.IntegerField(verbose_name='Мусорность')),
                ('views', models.IntegerField(default=0, verbose_name='Кол-во просмотров')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Создано')),
                ('work_exp', models.CharField(blank=True, default='Не требуется опыт работы', max_length=32, null=True, verbose_name='Опыт работы')),
                ('information', tinymce.models.HTMLField(verbose_name='Информация')),
                ('gender', models.CharField(default='Не указан', max_length=15, verbose_name='Пол')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.company', verbose_name='Компания')),
                ('tags', models.ManyToManyField(blank=True, to='tags.tags', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'db_table': 'wrk_vacancies',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='ID')),
                ('title', models.CharField(max_length=128, validators=[src.modules.work.models.non_empty_charfield_validation], verbose_name='Тайтл')),
                ('description', models.CharField(max_length=1024, validators=[src.modules.work.models.non_empty_charfield_validation], verbose_name='Описание')),
                ('salary', models.CharField(default='Не указано', max_length=50, verbose_name='Желаемая зарплата')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('email', models.CharField(max_length=32, validators=[src.modules.work.models.non_empty_charfield_validation], verbose_name='Почта')),
                ('avatar', models.ImageField(default='no_photo.png', upload_to=src.modules.work.models.upload_image_resume, verbose_name='Аватар')),
                ('work_exp', models.CharField(default='Нет опыта работы', max_length=32, verbose_name='Опыт работы')),
                ('gender', models.CharField(default='Не указан', max_length=10, verbose_name='Пол')),
                ('views', models.IntegerField(default=0, verbose_name='Кол-во просмотров')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено?')),
                ('is_moderated', models.BooleanField(default=False, verbose_name='Промодерировано?')),
                ('created_at', models.DateField(auto_now=True, verbose_name='Создано')),
                ('updated_at', models.DateField(auto_now_add=True, verbose_name='Обновлено')),
                ('skills', models.ManyToManyField(to='work.skill')),
                ('specialization', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.specialty')),
                ('tags', models.ManyToManyField(blank=True, to='tags.tags', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
                'db_table': 'wrk_resumes',
                'ordering': ['id'],
            },
        ),
    ]
