# Generated by Django 4.0.2 on 2022-11-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.ManyToManyField(to='work.Skill'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.Tags', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.Tags', verbose_name='Теги'),
        ),
    ]
