# Generated by Django 4.0.3 on 2022-11-24 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_alter_resume_skills_alter_resume_tags_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='avatar',
            new_name='image',
        ),
    ]
