# Generated by Django 4.0.3 on 2022-11-27 08:55

from django.db import migrations, models
import src.modules.work.models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_rename_avatar_resume_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='avatar',
            field=models.ImageField(default='not-found.png', upload_to=src.modules.work.models.upload_image_to, verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='image',
            field=models.ImageField(default='not-found.png', upload_to=src.modules.work.models.upload_image_resume, verbose_name='Аватар'),
        ),
    ]
